version: '3.8'

services:
  updater_module:
    env_file:
      - "../.env"
    build:
      context: .
    container_name: updater_module
    restart: always
    ports:
      - "9085:8080"
    environment:
      MODULE_GROUP_ID: UPDATER_GROUP_ID
#    deploy:
#      mode: replicated
#      replicas: 2

